name: CI Initialise

on:
  push:
    branches:
      - '*'

jobs:
  initialise:
    runs-on: ubuntu-latest
    steps:
      - name: Print initialisation message
        run: echo "CI step initialising"

