name: Verify Secrets

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  verify-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check POSTGRES_USER
        run: |
          if [ -n "${{ secrets.POSTGRES_USER }}" ]; then
            echo "✅ POSTGRES_USER is set"
          else
            echo "❌ POSTGRES_USER is not set"
            exit 1
          fi

      - name: Check POSTGRES_PASSWORD
        run: |
          if [ -n "${{ secrets.POSTGRES_PASSWORD }}" ]; then
            echo "✅ POSTGRES_PASSWORD is set"
          else
            echo "❌ POSTGRES_PASSWORD is not set"
            exit 1
          fi

      - name: Check OPIK_API_KEY
        run: |
          if [ -n "${{ secrets.OPIK_API_KEY }}" ]; then
            echo "✅ OPIK_API_KEY is set"
          else
            echo "❌ OPIK_API_KEY is not set"
            exit 1
          fi

      - name: Check OPIK_WORKSPACE
        run: |
          if [ -n "${{ secrets.OPIK_WORKSPACE }}" ]; then
            echo "✅ OPIK_WORKSPACE is set"
          else
            echo "❌ OPIK_WORKSPACE is not set"
            exit 1
          fi

      - name: Check OPIK_PROJECT_NAME
        run: |
          if [ -n "${{ secrets.OPIK_PROJECT_NAME }}" ]; then
            echo "✅ OPIK_PROJECT_NAME is set"
          else
            echo "❌ OPIK_PROJECT_NAME is not set"
            exit 1
          fi

      - name: Check OPENAI_API_KEY
        run: |
          if [ -n "${{ secrets.OPENAI_API_KEY }}" ]; then
            echo "✅ OPENAI_API_KEY is set"
          else
            echo "❌ OPENAI_API_KEY is not set"
            exit 1
          fi

      - name: All Secrets Verified
        run: |
          echo "🎉 All secrets are properly set and accessible!"
          echo "This confirms that your secrets were successfully configured." 